config/routes.rb
Gallerybook::Application.routes.draw do

  resources :friendships

  get "allgalleries" => "galleries#allgalleries"

  devise_for :users, path_name: {sign_in: "login", sign_out: "logout"}
  
  resources :galleries do
    member do 
      get 'xxx'
    end
    resources :comments
  end

  resources :users

  resources :photos do
    resources :comments
  end

  root to: "galleries#index"

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :gallery
	has_many :comments, as: :commentable
	mount_uploader :picture, PictureUploader
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])
    @commentable = @photo
    @comments = @commentable.comments
    @comment = Comment.new
    @comment.user_id = current_user.id
  end

  # GET /photos/new
  def new
    @gallery = Gallery.find(params[:id])
    @photo = Photo.new
    @photo.gallery_id = params[:id]
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:picture, :description, :gallery_id)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for @photo, :html => {:multipart => true} do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :picture %>
    <%= f.file_field :picture %>
  </div>
  <br>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <br>
  <div class="field">
    <%= f.label :gallery_id %>
    <%= f.number_field :gallery_id %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<br>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th>Description</th>
      <th>Gallery</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= image_tag(photo.picture.url, :width => 100) if photo.picture.present? %></td>
        <td><%= photo.description %></td>
        <td><%= photo.gallery_id %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p>รวมทั้งหมด <%= @photos.length %>  รูป</p>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<!-- <%= render 'form' %> -->

<div class="row">
  <% @gallery.photos.each do |photo| %>
    <div class="span4">
      <div class="img">
        <%= link_to image_tag(photo.picture.url, :width => 200), photo_path(photo) if photo.picture.url.present? %>
      </div>

      <div style="text-align:center;">
        <h3><%= photo.name %></h3>
      </div>
    </div>
  <% end %>
</div>

<%= form_for Photo.new do |f| %>
	<%= f.label :picture, "Upload photos to gallery" %>
	<%= f.file_field :picture, multiple: true, name: "photo[picture]" %>
<% end %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<div style="text-align:center;">
	<p><strong><%= @photo.name %></strong></p>

<p><%= image_tag(@photo.picture_url, :width => 300) if @photo.picture.present? %></p>
<p><%= @photo.description %></p>
<br>
<h5>Comments</h5>
</div>

<div class="center">
	<%= render "comments/comments" %>
	<%= render "comments/form" %>
</div>

<br>

<%= link_to 'Galleries', galleries_path %> |
<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', gallery_path(@photo.gallery_id) %>