config/routes.rb
Gallerybook::Application.routes.draw do

  resources :friendships

  get "allgalleries" => "galleries#allgalleries"

  devise_for :users, path_name: {sign_in: "login", sign_out: "logout"}
  
  resources :galleries do
    member do 
      get 'xxx'
    end
    resources :comments
  end

  resources :users

  resources :photos do
    resources :comments
  end

  root to: "galleries#index"

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	has_many :photos
	has_many :comments, as: :commentable
	belongs_to :user
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.find(:all, :conditions => {:user_id => current_user.id})
  end

  def allgalleries
    @galleries = Gallery.all
  end

  def xxx

  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery = Gallery.find(params[:id])
    # @photos = Photo.find(:all, :conditions => { :gallery_id => @gallery.id})
    @photos = @gallery.photos
    @commentable = @gallery
    @comments = @commentable.comments
    @comment = Comment.new
    @comment.user_id = current_user.id
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
    @gallery.user_id = params[:user_id]
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gallery }
      else
        format.html { render action: 'new' }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:gallert_name, :description, :user_id)
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.erb
<%= form_for @gallery, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :gallert_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :gallert_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_id, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                galleries_path, :class => 'btn' %>
  </div>
<% end %>

app/views/galleries/allgalleries.html.erb
<%- model_class = Gallery -%>

<div class="page-header">
  <h5><u>All <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></u></h5>
</div>

<div class="row">
  <% @galleries.each do |gallery| %>
    <div class="span4">
      <div class="img" style="padding-bottom:0;"><%= link_to image_tag(gallery.photos.first.picture.url), gallery_path(gallery) if gallery.photos.first.picture.url.present? %>
        <div class="number">
          <div style="position:absolute;top:30%;left:30%;"><%= link_to gallery.photos.length, gallery_path(gallery) %>
          </div>
        </div>
      </div>

      <div style="margin-top:-30px;"><h4><%= link_to gallery.gallert_name, gallery_path(gallery) %></h4></div>
      <div><%= link_to gallery.description, gallery_path(gallery) %></div>
    </div><!-- .span4 -->
  <% end %>
</div><!-- .row -->

  <br>

app/views/galleries/edit.html.erb
<%- model_class = Gallery -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/galleries/index.html.erb
<%- model_class = Gallery -%>

<div class="intro" style="text-align:center;">

  <h5 style="display:inline;"><u>Hello</u> </h5>
  <p style="display:inline;"><%= current_user.username %></p>
  <h5><u>Welcome to Gallery Book :)</u></h5>
  <%= link_to "New Gallery",
              new_gallery_path(:user_id => current_user.id),
              :class => 'btn btn-success' %>

</div>

<div class="page-header">
  <h5><u>My <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></u></h5>
</div>

<div class="row">
  <% @galleries.each do |gallery| %>
    <div class="span4">
      <div class="img" style="padding-bottom:0;"><%= link_to image_tag(gallery.photos.first.picture.url), gallery_path(gallery) if gallery.photos.first.picture.url.present? %>
        <div class="number">
          <div style="position:absolute;top:30%;left:30%;"><%= link_to gallery.photos.length, gallery_path(gallery) %>
          </div>
        </div>
      </div>

      <div style="margin-top:-30px;"><h4><%= link_to gallery.gallert_name, gallery_path(gallery) %></h4></div>
      <div><%= link_to gallery.description, gallery_path(gallery) %></div>
    </div><!-- .span4 -->
  <% end %>
</div><!-- .row -->

  <br>

app/views/galleries/new.html.erb
<%- model_class = Gallery -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/galleries/show.html.erb
<%- model_class = Gallery -%>
<div class="page-header">
  <div class="row">
    <div class="span5">
      <h1><%=t '.title', :default => @gallery.gallert_name %></h1>
      <p><%= @gallery.description %></p>
    </div>

    <div class="span7 CommentNumber">
      <div style="position:absolute;top:35%;left:30%;">
        <p><%= @gallery.photos.length %></p>
      </div>
    </div>
  </div>
</div>

<!-- <dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:gallert_name) %>:</strong></dt>
  <dd><%= @gallery.gallert_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @gallery.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @gallery.user_id %></dd>
</dl> -->

<div class="row">
  <% @gallery.photos.each do |photo| %>
    <div class="span4">
      <div class="img">
        <%= link_to image_tag(photo.picture.url, :width => 200), photo_path(photo) if photo.picture.url.present? %>
        <div class="bubble" style="bottom:50px;left:160px;">
          <div style="position:absolute;top:30%;left:40%;font-size: 2.2em;">
            <%= photo.comments.length %>
          </div>
        </div>
      </div>

      <div style="margin-top:-30px;margin-bottom:40px;">
        <p><%= photo.name %></p>
      </div>
    </div>
  <% end %>
</div>

<div class="CommentNumber addNew">
  <div style="position:absolute;top:35%;left:25%;font-size: 2.2em;">
    <%= link_to "+", new_photo_path(:id => @gallery.id) %>
  </div>
</div>

<br>

<div class="center">
<%= content_tag :div, id: "comments", data: {url: gallery_comments_url(@gallery)} do %>
  <h5><u>Comments</u></h5>
  <%= render "comments/comments" %>
<% end %>
  <p>Add comment</p>
  <%= render "comments/form" %>
</div>

app/views/galleries/xxx.html.erb
xxxx